image:
  repository: "carex/wordpress-prod" #"S-Stepanenko/wordpress-prod"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wp.k8s-37.sa

persistentVolumeClaim:
  storageSize: 10Gi

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: wordpress-mysql:3306
  - name: WORDPRESS_DB_NAME
    value: wordpressdb
  - name: WORDPRESS_DB_USER
    value: root
  - name: WORDPRESS_DB_PASSWORD
    value: root
  - name: WP_DEBUG_LOG
    value: root
